### ISSUE TITLE
 LDSC values

### ISSUE THREAD

**Issue by Yab29** [ZhaotongL/MVMR-cML#1]
Can the method calculate bivariate LDSC values or does it require pre-calculated values? If it does require pre-calculated values, which methods or packages were used to obtain these bivariate LDSC values? Thank you.

**Comment by ZhaotongL** [comment]
Hi, currently we require the user to input their precalculated correlation matrix. We used bivariate LDSC regression to obtain this in the example. A detailed tutorial of LDSC can be found here: https://github.com/bulik/ldsc/wiki.

**Comment by Yab29** [comment]
Thank you.

**Comment by 1667857557** [comment]
Can you give me more detail about the composition (h2, Lambda GC or Intercept) of the correlation matrix? and what order it needs

**Comment by ZhaotongL** [comment]
> Can you give me more detail about the composition (h2, Lambda GC or Intercept) of the correlation matrix? and what order it needs

We will need the intercept term from the bivariate LDSC regression.

**Comment by 1667857557** [comment]
> > Can you give me more detail about the composition (h2, Lambda GC or Intercept) of the correlation matrix? and what order it needs
> 
> We will need the intercept term from the bivariate LDSC regression.

For example, we need to use the 3 phenotypes that consider as the exposure in MVMR and 1 phenotype that use as the outcome in MVMR to calculate the LDSC score between each other 16(2^4) times, and the intercept terms of the result were used to built correlation matrix, is it?

**Comment by ZhaotongL** [comment]
> > > Can you give me more detail about the composition (h2, Lambda GC or Intercept) of the correlation matrix? and what order it needs
> > 
> > 
> > We will need the intercept term from the bivariate LDSC regression.
> 
> For example, we need to use the 3 phenotypes that consider as the exposure in MVMR and 1 phenotype that use as the outcome in MVMR to calculate the LDSC score between each other 16(2^4) times, and the intercept terms of the result were used to built correlation matrix, is it?

Since the correlation matrix is symmetric, and the diagonal will be ones, for 4 phenotypes, you only need to calculate bivariate LDSC regression on every pair of them, which is 6 times.
