### ISSUE TITLE
Error: chol(): decomposition failed

### ISSUE THREAD

**Issue by JINCHENG-bio** [ZhaotongL/MVMR-cML#2]
Hello,
Thanks to the authors for developing this advanced algorithm for performing MVMR. However, I have encountered a problem as described below:
When i run 
```
 MVcML_res = MVmr_cML_DP(b_exp=mvdat$exposure_beta,
                           b_out=as.matrix(mvdat$outcome_beta),
                           se_bx=mvdat$exposure_se,
                           Sig_inv_l=Sig_inv_l,
                           n = n,
                           num_pert = 5000, 
                           K_vec = 0:20 
                           )
```
I got this error:
 
`Error: chol(): decomposition failed `
Due to my limited knowledge of mathematics, I did some searching and learned that this error seems to be reported because
the Cholesky decomposition /chol() requires the input matrix to be positive definite.
 
The whole rho_mat input as following:
```
    [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]    [,8]    [,9]
 [1,]    1  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
 [2,]    0  1.0000  0.0697  0.6134  0.3096  0.4475  0.5030  0.5344 -0.0241
 [3,]    0  0.0697  1.0000 -0.5164 -0.5121 -0.5705 -0.5684 -0.5783 -0.0063
 [4,]    0  0.6134 -0.5164  1.0000  0.6756  0.9253  0.9432  0.9518  0.0037
 [5,]    0  0.3096 -0.5121  0.6756  1.0000  0.7062  0.6930  0.6500 -0.0194
 [6,]    0  0.4475 -0.5705  0.9253  0.7062  1.0000  1.1182  1.0903 -0.0007
 [7,]    0  0.5030 -0.5684  0.9432  0.6930  1.1182  1.0000  1.1056 -0.0028
 [8,]    0  0.5344 -0.5783  0.9518  0.6500  1.0903  1.1056  1.0000 -0.0042
 [9,]    0 -0.0241 -0.0063  0.0037 -0.0194 -0.0007 -0.0028 -0.0042  1.0000
```

Calculating the eigenvalues of the matrix reveals that the matrix is indeed not positive definite.

```
 eigenvalues <- eigen(rho_mat)$values
 eigenvalues
 [1]  5.21631024  1.10700116  1.00000000  0.99777578  0.47417463  0.33415360
[7]  0.08965039 -0.09758973 -0.12147607
```

Each value in the matrix is an intercept calculated by bivariate ldsc (Brendan et al.), except for GWAS dataset 1, which was determined to have no overlap with the other 2-9 GWAS dataset samples and assigned a value of 0.
In addition, dataset 2-9 are all from the UKB population, so there is a large degree of overlap.

I guess it is due to a problem with the rho matrix not being positive definite, but I don't know how to fix it.
Hopefully you can help me out with this, many thanks!!!

Looking forward to your response
best wishes!

jincheng

**Comment by ZhaotongL** [comment]
Hi Jincheng,

The correlation matrix seemed problematic to me. Each element in the matrix is a correlation so it should be between -1 and 1. But you have some values larger than 1 in the matrix and many of them were close to 1 which also seemed unnormal to me. You may want to check your ldsc procedure, or you can try to use another way to compute, e.g. use the correlation between Z-scores of null SNPs (you can refer to the MVMR-cML paper and some references therein).

**Comment by JINCHENG-bio** [comment]
Thanks a lot! It works well after using the correlation between Z-scores of null SNPs.
