### ISSUE TITLE
Ordering of values in Sig_inv_l

### ISSUE THREAD

**Issue by noahlorinczcomi** [ZhaotongL/MVMR-cML#3]
It doesn't seem to be explicitly stated anywhere in the software, nor implied, that the $(p+1)\times(p+1)$ matrix `Sig_inv_l[[i]]` is expected to have elements corresponding to the $p$ exposures in the upper-left $p\times p$ submatrix and to the outcome in the bottom right. Positioning the outcome at the first, upper-left index of this matrix will produce causal estimates that are very unexpected, but everything in the code will appear to be working correctly. You may consider just adding something to the documentation of `invcov_mvmr()` or `MVmr_cML_DP()`. Also the `invcov_mvmr()` function does not need to store `Sig_l`.

**Comment by ZhaotongL** [comment]
Thanks! It is added in the description now.
